version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/app
    depends_on:
      - django
      - demo1
      - demo2

  django:
    build: ./django_hub
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000 --reload
    expose:
      - "8000"
    volumes:
      - ./django_hub:/app

  demo1:
    build: ./streamlit/streamlit_demo
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0 --server.baseUrlPath="/demo1" --server.enableCORS=false --server.enableXsrfProtection=false
    expose:
      - "8501"

  demo2:
    build: ./streamlit/streamlit_demo2
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0 --server.baseUrlPath="/demo2" --server.enableCORS=false --server.enableXsrfProtection=false
    expose:
      - "8501"